services:
  api1: &api
    image: avalonbits/rinha2024:latest
    hostname: api1
    container_name: rinhaapi1
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '175MB'
    networks:
      - app-network
    volumes:
      - sqlitedb:/tmp
    restart: always
  api2:
    <<: *api
    hostname: api2
    container_name: rinhaapi2
    volumes:
      - sqlitedb:/tmp
    ports:
      - "6060:5000"
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: rinhaproxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '200MB'

networks:
  app-network:
volumes:
  sqlitedb:

