// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import ()

type Limit struct {
	Cid   int64
	Value int64
}

type Transaction struct {
	Cid         int64
	Tid         string
	Value       int64
	Description string
	CreatedAt   string
}
