// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package repo

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO Transaction (cid, tid, value, description, created_at)
       VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	Cid         int64
	Tid         string
	Value       int64
	Description string
	CreatedAt   int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.Cid,
		arg.Tid,
		arg.Value,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}
